### ISSUE TITLE
Request for advancement to owner in Web and marketing area

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/governance#15]
In line with the [contributor ladder](https://github.com/guacsec/guac/blob/main/CONTRIBUTING.md#contributor-ladder), I am requesting to be advanced to owner in the Web and marketing area and receive write access to guacsec/guac-landing.

I'm requesting to skip directly from contributor to owner because of the new nature of the area. I've made significant contributions to the technical and content aspects of this area.

This request requires a majority approval from the current maintainers.

Work samples:

* Convert blog from single page to per-file (guacsec/guac-landing#39)
* Add RSS feed to blog (guacsec/guac-landing#41)
* Release announcements for v0.7.0 (guacsec/guac-landing#38)
* Community page improvements (guacsec/guac-landing#42)
* Basic documentation for local build/test (guacsec/guac-landing#30)

**Comment by lumjjb** [comment]
Hi @funnelfiasco can you add the list of PRs/efforts so that we can add that to the contributor ladder decision! thanks!

**Comment by funnelfiasco** [comment]
> Hi @funnelfiasco can you add the list of PRs/efforts so that we can add that to the contributor ladder decision! thanks!

Done!

**Comment by mlieberman85** [comment]
I'm in support of this.

**Comment by mihaimaruseac** [comment]
I'm +1 on this, having reviewed some of the listed PRs

**Comment by pxp928** [comment]
+1! Thanks

**Comment by jeffmendoza** [comment]
+1 Thanks for your contributions!
