### ISSUE TITLE
Add LFX Insights integration

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/governance#17]
Opening this to track adding the [GitHub integration](https://docs.linuxfoundation.org/lfx/community-management/integrations/github-integration) for [Insights](https://insights.lfx.linuxfoundation.org/foundation/openssf/projects) as discussed in today's Maintainers Meeting. This is a quick process so once Bennett has access, it should only take a few minutes.

- [x] Maintainer: Add @bbpursell1 to GitHub org as an owner
- [x] @bbpursell1: Enable integration
- [x] Maintainer: Remove bbpursell1 from GitHub org

**Comment by funnelfiasco** [comment]
Mike added Bennett and I relayed the information.

**Comment by bbpursell1** [comment]
Integration added.  Currently ingesting data.  It may take up to a day or so to process all the data and show up in Insights.  You should be able to remove me now.  The project should show up as a subproject of the Supply Chain Integrity Working Group once the data is loaded: https://insights.lfx.linuxfoundation.org/foundation/openssf/overview/github?project=diossf

**Comment by funnelfiasco** [comment]
Looks like the data are populated in https://insights.lfx.linuxfoundation.org/foundation/openssf/overview/github?project=guac 

And Bennett is no longer in the org. I think this counts as complete. Thanks for the help, everyone!
