### ISSUE TITLE
Consolidate office hours times

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/governance#26]
The office hours timing has led to confusion in getting the calendar right. @pxp928 and I had a conversation about it and we think it would be best to consolidate into a single time every two weeks for simplicity's sake. We don't get a ton of folks dropping in anyway, so having alternating times may be solving for a problem we don't have.

I propose 11am Eastern on alternate Fridays, as that would keep it from being too late in EMEA (5pm Central European Time) and too early for the western Americas (8am Pacific).

I'll share this on the mailing list and in Slack for community feedback and ask maintainers to give it a thumbs up or thumbs down in the 26 August maintainers meeting. This way we can have a decision a few days in advance of the next scheduled office hours.

**Comment by pxp928** [comment]
+1

**Comment by mihaimaruseac** [comment]
+1 from me too! thank you

**Comment by funnelfiasco** [comment]
The consensus in today's meeting was to make this change, so I'll start the implementation.

- [ ] Coordinate with OpenSSF staff to update the calendar
- [ ] Update the website
- [ ] Blog post announcing it
- [ ] Slack and mailing list posts

**Comment by funnelfiasco** [comment]
Implemented and announced!
