### ISSUE TITLE
Hacktoberfest 2024

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/governance#30]
As part of our work to improve GUAC's documentation, I propose we participate in [Hacktoberfest](https://hacktoberfest.com/) this year. We will add the hacktoberfest topic to the [guacsec/guac-docs repo](https://github.com/guacsec/guac-docs) and [guacsec/guac-visualizer](https://github.com/guacsec/guac-visualizer) and only those repos.

@funnelfiasco will be responsible for coordinating, replying, and reviewing submissions. Kusari will send some GUAC swag to anyone who participates in the repo during the month of October.

Objections? Questions?

**Comment by funnelfiasco** [comment]
I'm not currently an owner in the docs area, so I'll need some help when it comes time to add the topic and merge PRs, etc, but I can make sure that coordination happens.

**Comment by mihaimaruseac** [comment]
I can help with reviewing and merging

**Comment by funnelfiasco** [comment]
Updated to add guac-visualizer to the proposal.
