### ISSUE TITLE
Move maintainer meeting into the public

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/governance#5]
The maintainer meeting will move into the public for transparency and community-building. 

The rough steps involved:

- [x] Draft meeting request (@funnelfiasco)
- [x] Approve content (maintainers)
- [x] Create meeting (OpenSSF Ops)
- [x] Announce public meeting (@funnelfiasco)

**Comment by funnelfiasco** [comment]
@guacsec/guac-maint any concerns with the following?

**Title:** GUAC Maintainers meeting
**Date/time:** Mondays at 11 AM Eastern

**Description:** 
Regular meeting for GUAC maintainers to coordinate development work. The meeting is open to interested community members, but is primarily for maintainer discussion. For general questions and discussion, join us in #guac on the OpenSSF Slack.

**Comment by pxp928** [comment]
LGTM

**Comment by funnelfiasco** [comment]
Meeting request sent to Ops

**Comment by funnelfiasco** [comment]
Meeting created: https://www.google.com/calendar/event?eid=NjBrdDZ0MzVsbTRiNjNqbGhpajVxMXQ0MGJfMjAyNDA2MDNUMTUwMDAwWiBzNjN2b2VmaHA1aTlwZmx0YjVxNjduZ3Blc0Bn&ctz=America/New_York

It will start on June 3! (I've asked them to create and attach a Google Doc, which will be done momentarily). I'll make a public announcement next week.
