### ISSUE TITLE
Create separate announcement and discussion mailing lists?

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/governance#7]
As part of #6, we should consider creating separate announcement and discussion mailing lists. This would allow the community to have email-based discussion about GUAC issues but still preserve a low-traffic announcement list for those who don't want the discussion emails.

I am generally in favor of such a split, but it's not clear to me that we need it at this point. I see three directions we could go:

1. Keep a single list and make it explicitly announcement-only
2. Keep a single list for discussion and announcements. If we reach a point where this becomes a problem, we can create a separate announcement list.
3. Create an announcement and a discussion list now.

My recommendation is option 2. I'll leave this open for community input and ask the maintainers to make a decision at their 3 June meeting.

**Comment by mlieberman85** [comment]
I agree with 2.

**Comment by lumjjb** [comment]
In favor for 2 as well. I don't think we have too much traffic in the past that warrants a separate list.

**Comment by pxp928** [comment]
2 gets my vote also.

**Comment by funnelfiasco** [comment]
The consensus seems to be option 2, so I'm proceeding with that.
